=== BenPhegan/renderconfig/source/RenderConfig.Core/Configuration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="RenderConfig" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="RenderConfig" msdata:IsDataSet="true" msdata:Locale="en-US">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Includes" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Include" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="file" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Configurations" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Configuration" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                   <xs:sequence>
                    <xs:element name="EnvironmentVariables" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="EnvironmentVariable" nillable="true" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent msdata:ColumnName="EnvironmentVariable_Text" msdata:Ordinal="1">
                                <xs:extension base="xs:string">
                                  <xs:attribute name="variable" type="xs:string" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="TargetFiles" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="XML" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Add" type="XmlAdd" nillable="true" minOccurs="0" maxOccurs="unbounded" />
                                <xs:element name="Update" type="XmlUpdate" nillable="true" minOccurs="0" maxOccurs="unbounded" />
                                <xs:element name="Delete" type="XmlDelete" nillable="true" minOccurs="0" maxOccurs="unbounded" />
                                <xs:element name="Replace" type="XmlReplace" nillable="true" minOccurs="0" maxOccurs="unbounded" />
                              </xs:sequence>
                              <xs:attribute name="source" type="xs:string" />
                              <xs:attribute name="destination" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="INI" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Add" type="IniAdd" nillable="true" minOccurs="0" maxOccurs="unbounded" />
                                <xs:element name="Update" type="IniUpdate" nillable="true" minOccurs="0" maxOccurs="unbounded" />
                                <xs:element name="Delete" type="IniDelete" nillable="true" minOccurs="0" maxOccurs="unbounded" />
                                <xs:element name="Replace" type="IniReplace" nillable="true" minOccurs="0" maxOccurs="unbounded" />
                              </xs:sequence>
                              <xs:attribute name="source" type="xs:string" />
                              <xs:attribute name="destination" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="TXT" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Replace" type="IniReplace" nillable="true" minOccurs="0" maxOccurs="unbounded" />
                              </xs:sequence>
                              <xs:attribute name="source" type="xs:string" />
                              <xs:attribute name="destination" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Name" type="xs:string"></xs:attribute>
                  <xs:attribute name="Depends" type="xs:string" ></xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="XmlAdd">
    <xs:simpleContent msdata:ColumnName="XmlAdd_Text">
      <xs:extension base="xs:string">
        <xs:attribute name="xpath" type="xs:string" />
        <xs:attribute name="attribute" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="XmlUpdate">
    <xs:simpleContent msdata:ColumnName="XmlUpdate_Text">
      <xs:extension base="xs:string">
        <xs:attribute name="xpath" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="XmlDelete">
    <xs:simpleContent msdata:ColumnName="XmlDelete_Text">
      <xs:extension base="xs:string">
        <xs:attribute name="xpath" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="XmlReplace">
    <xs:simpleContent msdata:ColumnName="XmlReplace_Text">
      <xs:extension base="xs:string">
        <xs:attribute name="regex" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IniAdd">
      <xs:simpleContent msdata:ColumnName="IniAdd_Text">
        <xs:extension base="xs:string">
          <xs:attribute name="section" type="xs:string" />
          <xs:attribute name="key" type="xs:string" />
        </xs:extension>
      </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IniUpdate">
      <xs:simpleContent msdata:ColumnName="IniUpdate_Text">
        <xs:extension base="xs:string">
          <xs:attribute name="section" type="xs:string" />
          <xs:attribute name="key" type="xs:string" />
        </xs:extension>
      </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IniDelete">
      <xs:attribute name="section" type="xs:string" />
      <xs:attribute name="key" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="IniReplace">
      <xs:simpleContent msdata:ColumnName="IniReplace_Text">
        <xs:extension base="xs:string">
          <xs:attribute name="regex" type="xs:string" />
        </xs:extension>
      </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TxtReplace">
      <xs:simpleContent msdata:ColumnName="TxtReplace_Text">
        <xs:extension base="xs:string">
          <xs:attribute name="regex" type="xs:string" />
        </xs:extension>
      </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== BenPhegan/renderconfig/source/RenderConfig.Core.Tests/Examples/config.ini.xml
<RenderConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Configuration.xsd">
  <Configurations>
    <Configuration Name="inifilemodifier" >
      <TargetFiles>
        <INI source="test.ini" destination="original.ini"/>
        <INI source="test.ini" >
          <Add section="Logging" key="CommonSetting">Value for common setting</Add>
          <Delete section="Logging" key="MessageColumns"/>
          <Update section="Logging" key="MaxFileSize">69</Update>
          <Add section="NewSection" key="FromCommon">BLAH!</Add>
        </INI>
      </TargetFiles>
    </Configuration>

    <Configuration Name="inireplace" >
      <TargetFiles>
        <INI source="test.ini" destination="original.ini" />
        <INI source="test.ini" >
          <Replace regex="Expansion">Replacement</Replace>
        </INI>
      </TargetFiles>
    </Configuration>

    <Configuration Name="inimissingsection" >
      <TargetFiles>
        <INI source="test.ini" >
          <Update section="Missing" key="MaxFileSize">69</Update>
        </INI>
      </TargetFiles>
    </Configuration>

    <Configuration Name="inimissingkey" >
      <TargetFiles>
        <INI source="test.ini" >
          <Update section="Logging" key="MissingKey">69</Update>
        </INI>
      </TargetFiles>
    </Configuration>

  </Configurations>
</RenderConfig>

=== BenPhegan/renderconfig/source/RenderConfig.Core.Tests/Examples/config.xml.xml
<RenderConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Configuration.xsd">
  <Includes>
    <Include file="config.entity.configuration.xml"/>
  </Includes>
  <Configurations>
    <Configuration Name="xmldeletens">
      <TargetFiles>
        <XML source="test.ns.xml" destination="xmldelete.ns.xml">
          <Delete xpath="/configuration/nhibernate/add[@key='hibernate.dialect']"/>
          <Delete xpath="/configuration/nhibernate/add[@key='hibernate.connection.driver_class']/@value"/>
          <Delete xpath="/configuration/configSections/section"/>
        </XML>
      </TargetFiles>
    </Configuration>

    <Configuration Name="xmlfilemodifier" Depends="xmladd, xmladdns, xmldelete, xmldeletens, xmlupdate, xmlupdatens"/>

    <Configuration Name="xmladdns">
      <TargetFiles>
        <XML source="test.ns.xml" destination="xmladd.ns.xml">
          <Add attribute="value" xpath="/configuration/configSections/section">xmladd</Add>
          <Add xpath="/configuration/nhibernate"><![CDATA[<Node><Test>xmladd</Test></Node>]]></Add>
          <Add xpath="/configuration/nhibernate">SimpleNode</Add>
          <Add attribute="random" xpath="/configuration/nhibernate/add[@key='hibernate.dialect']">xmladd</Add>
        </XML>
      </TargetFiles>
    </Configuration>

    <Configuration Name="xmldelete">
      <TargetFiles>
        <XML source="test.xml" destination="xmldelete.xml">
          <Delete xpath="/configuration/nhibernate/add[@key='hibernate.dialect']"/>
          <Delete xpath="/configuration/nhibernate/add[@key='hibernate.connection.driver_class']/@value"/>
          <Delete xpath="/configuration/configSections/section"/>
        </XML>
      </TargetFiles>
    </Configuration>

    <Configuration Name="xmlreplacebad">
      <TargetFiles>
        <XML source="test.xml" destination="xmlreplace.xml">
          <Replace regex="/>">></Replace>
        </XML>
      </TargetFiles>
    </Configuration>

    <Configuration Name="xmladd">
      <TargetFiles>
        <XML source="test.xml" destination="xmladd.xml">
          <Add attribute="value" xpath="/configuration/configSections/section">xmladd</Add>
          <Add xpath="/configuration/nhibernate"><![CDATA[<Node><Test>xmladd</Test></Node>]]></Add>
          <Add xpath="/configuration/nhibernate">SimpleNode</Add>
          <Add attribute="random" xpath="/configuration/nhibernate/add[@key='hibernate.dialect']">xmladd</Add>
        </XML>
      </TargetFiles>
    </Configuration>

    <Configuration Name="xmlreplace">
      <TargetFiles>
        <XML source="test.ns.xml" destination="xmlreplace.ns.xml">
          <Replace regex="Random">ReplacementRandom</Replace>
        </XML>
        <XML source="test.xml" destination="xmlreplace.xml">
          <Replace regex="Random">ReplacementRandom</Replace>
        </XML>
      </TargetFiles>
    </Configuration>

    <Configuration Name="xmlupdatens">
      <TargetFiles>
        <XML source="test.ns.xml" destination="xmlupdate.ns.xml">
          <Update xpath="/configuration/nhibernate/add[@key='hibernate.dialect']/@value">xmlupdate</Update>
          <Update xpath="/configuration/Random">xmlupdate</Update>
        </XML>
      </TargetFiles>
    </Configuration>

    <Configuration Name="variables">
      <!-- The environment variable below will only get used if Variables is not used as a dependency which also defines this variable-->
      <EnvironmentVariables>
        <EnvironmentVariable variable="VariableSetting">variables</EnvironmentVariable>
      </EnvironmentVariables>
      <TargetFiles>
        <XML source="test.xml">
          <Update xpath="/configuration/Random">$(VariableSetting)</Update>
        </XML>
      </TargetFiles>
    </Configuration>

    <Configuration Name="variabletest1" Depends="variables">
      <EnvironmentVariables>
        <EnvironmentVariable variable="VariableSetting">variabletest1</EnvironmentVariable>
      </EnvironmentVariables>
    </Configuration>

    <Configuration Name="variabletest2" Depends="variables">
      <EnvironmentVariables>
        <EnvironmentVariable variable="VariableSetting">variabletest2</EnvironmentVariable>
      </EnvironmentVariables>
    </Configuration>
    
  </Configurations>
</RenderConfig>

=== BenPhegan/renderconfig/source/RenderConfig.Core.Tests/Examples/config.other.xml
<RenderConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Configuration.xsd">
  <Configurations>
    <Configuration Name="variablesubstitution">
      <TargetFiles>
        <XML source="test.xml" destination="variablesubsingle.xml">
          <Update xpath="/configuration/Random">$(TEMP)</Update>
        </XML>
        <XML source="test.xml" destination="variablesubmultiple.xml">
          <Update xpath="/configuration/Random">$(TEMP)$(windir)</Update>
        </XML>
        <XML source="test.xml" destination="variablesubinterspersed.xml">
          <Update xpath="/configuration/Random">$(TEMP)blah$(windir)</Update>
        </XML>
      </TargetFiles>
    </Configuration>

    <Configuration Name="copy" >
      <TargetFiles>
        <XML source="test.ns.xml" />
      </TargetFiles>
    </Configuration>

    <Configuration Name="inputdirectory" >
      <TargetFiles>
        <XML source="test.xml" destination="test.xml" />
      </TargetFiles>
    </Configuration>

    <Configuration Name="preservestructure" >
      <TargetFiles>
        <XML source="testfiles\\test.xml" destination="test.xml" />
      </TargetFiles>
    </Configuration>

    <Configuration Name="config" Depends="variablesubstitution, MultipleDependencies">
      <TargetFiles>
        <INI source="test.ini">
          <Update section="Logging" key="File Name">$(TEMP)</Update>
          <Update section="Logging" key="Expansion1">$(TEMP)$(windir)</Update>
          <Update section="Logging" key="Expansion2">$(TEMP)blah$(windir)</Update>
        </INI>
      </TargetFiles>
    </Configuration>

    <Configuration Name="MultipleDependencies" Depends="Child1, Child2"/>

    <Configuration Name="Child1" Depends="Child3">
      <TargetFiles>
        <XML source="test.xml" destination="multipledependencies.xml">
          <Update xpath="/configuration/Random">Child1</Update>
        </XML>
      </TargetFiles>
    </Configuration>

    <Configuration Name="Child2">
      <TargetFiles>
        <XML source="test.xml" destination="multipledependencies.xml">
          <Update xpath="/configuration/Random">Child2</Update>
        </XML>
      </TargetFiles>
    </Configuration>

    <Configuration Name="Child3">
      <TargetFiles>
        <XML source="test.xml" destination="multipledependencies.xml">
          <Update xpath="/configuration/Random">Child3</Update>
        </XML>
      </TargetFiles>
    </Configuration>

  </Configurations>
</RenderConfig>
